algoritmo "Conversão de Euro para Reais"
// Função : Digitar quanto Euro possui e fazer a conversão para reais
// Autor : Nathalia Lima
// Data : 9/4/2019
// Seção de Declarações 
var
euro, conversao: real
inicio
// Seção de Comandos 
escreval ("Digite quanto de Euro você possui: ")
leia (euro)
conversao<-euro*4.34
escreval ("*1 Euro = R$4.34")
escreval ("O valor do Euro em Reais é", conversao)
fimalgoritmo
