algoritmo "Estoque"
// Função : Digitar quantidade de produtos no estoque e se estiver abaixo de 150 mostrar frase utilizando laço se
// Autor : Nathalia Lima
// Data : 18/4/2019
// Seção de Declarações 
var
qp:inteiro
inicio
// Seção de Comandos
escreval ("Digite a quantidade de produtos no estoque: ")
leia(qp)
se qp<150 entao
escreval ("O estoque está abaixo do necessário")
senao
escreval ("O estoque está bom")
fimse
fimalgoritmo
