algoritmo "Escolha de frases"
// Função : Exemplo da função do laço repita para mostrar frase até escolher para o programa parar
// Autor : Nathalia Lima
// Data : 6/6/2019
// Seção de Declarações 
var
opcao: inteiro
inicio
// Seção de Comandos 
repita
escreval ("1 - dizer olá!")
escreval ("2 - dizer oi!")
escreval ("0 - sair do progama")
leia (opcao)
se (opcao=1) entao
escreval ("olá!")
fimse
se (opcao=2) entao
escreval ("oi!")
fimse
ate (opcao=0)
fimalgoritmo
