algoritmo "Mostrar o maior número"
// Função : Escolher 5 idades e mostrar a maior idade utlizando laço de repetição para
// Autor : Nathalia Lima
// Data : 6/6/2019
// Seção de Declarações 
var
idade, c,maior: inteiro
inicio
// Seção de Comandos 

para c de 1 ate 5 faca
escreva ("Digite a idade: ")
leia (idade)
se idade>maior entao
maior<-idade
fimse
fimpara

escreval ("A maior idade é ",maior)

fimalgoritmo
