algoritmo "Mostrar valores"
// Função : Digitar dois valores e mostrá-los na tela
// Autor : Nathalia Lima
// Data : 9/4/2019
// Seção de Declarações 
var
a, b: inteiro
inicio
// Seção de Comandos
escreval ("Digite o primeiro valor")
leia (a)
escreval("Digite o segundo valor")
leia (b)
escreval ("O valor atual do primeiro número é: ", b)
escreval ("O valor atual do segundo número é: ", a)
fimalgoritmo
